limit_req_zone $binary_remote_addr zone=login_limit:10m rate=5r/m;
server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index login.html;

    server_tokens off;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()";

    location / {
        try_files $uri /login.html;
    }

    location /api/login {
        limit_req zone=login_limit burst=3 nodelay;
        limit_req_status 429;
        proxy_pass http://login-api:5000/login;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Referer $http_referer;
        proxy_set_header Origin $http_origin;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
    
    location /api/mfa {
    proxy_pass http://login-api:5000/mfa;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
}
